-- SQLite
-- Task 19 (clientes com duas ou mais locações)

SELECT NAME AS 'Nome',
  LASTNAME AS 'Sobrenome',
  COUNT(LOCATIONS.CUSTOMER_ID) AS 'Quantidade de locações'
  FROM CUSTOMERS JOIN LOCATIONS ON CUSTOMERS.ID = LOCATIONS.CUSTOMER_ID
  GROUP BY CUSTOMER_ID
  HAVING COUNT(LOCATIONS.CUSTOMER_ID) >= 2;